name: Update README.md

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout code

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser

    - name: Run Update Python Script
      run: |
        python post.py

    - name: Check Git Status
      run: |
        git status

    - name: Stage Changes
      run: |
        git add README.md # 파일을 업데이트한 경우

    - name: Commit Changes
      run: |
        git diff --quiet || (git commit -m "docs: Update README.md" && git push)
